package org.mitre.synthea.export.fr;

import org.hl7.fhir.r4.model.Coding;
import org.mitre.synthea.world.agents.Person;

import java.util.List;

public class FrFHIRContactRelationship {

    private static final List<Coding> POSSIBLE_RELATIONSHIPS = List.of(
            // RolePerson
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "ECON", "personne à prévenir en cas d'urgence"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "GUARD", "Responsable légal"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "QUAL", "Personne de confiance"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "POLHOLD", "Assuré ouvrant droit"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "CON", "Informateur"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "CAREGIVER", "Aidant"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "PAT", "aidé"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "PROV", "Professionnel de santé"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "AGNT", "Professionnel caractérisé par son rôle"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R260-HL7RoleClass/FHIR/TRE-R260-HL7RoleClass", "NOK", "personne de confiance"),
            //RelatedPerson
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "MTH", "Mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "FTH", "Père"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NMTH", "Mère biologique"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NFTH", "Père biologique"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPMTH", "Belle-mère - Épouse du père ou de la mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPFTH", "Beau-père - Époux du père ou de la mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GRMTH", "Grand-mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GRFTH", "Grand-père"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GGRMTH", "Arrière-grand-mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GGRFTH", "Arrière-grand-père"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "DAU", "Fille biologique"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SON", "Fils biologique"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "BRO", "Frère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SIS", "Soeur"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "HBRO", "Demi-frère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "HSIS", "Demi-soeur"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GRNDDAU", "Petite-fille"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GRNDSO", "Petit-fils"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "UNCLE", "Oncle"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "AUNT", "Tante"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NEPHEW", "Neveu"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NIECE", "Nièce"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "COUSIN", "Cousin(e)"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "HUSB", "Epoux"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "WIFE", "Epouse"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "DOMPART", "Concubin(e) ou partenaire PACS"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "ROOM", "Personne vivant sous le même toit"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "FRND", "Autre proche"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NBOR", "Voisin(e)"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "FAMMEMB", "Autre membre de la famille"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "EXT", "Autre membre de la famille sans lien génétique direct"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SPS", "Epoux ou Épouse"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "RESPRSN", "Responsable légal non membre de la famille"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "ADOPTF", "Père adoptif"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "ADOPTM", "Mère adoptive"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "ADOPTP", "Parent adoptif, au sens père ou mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "BROINLAW", "Beau-frère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "CHILD", "Enfant"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "CHLDADOPT", "Enfant adopté"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "CHLDFOST", "Enfant placé en famille d'accueil"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "CHLDINLAW", "Gendre ou belle-fille"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "COUSN", "Cousin(e)"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "DAUADOPT", "Fille adoptive"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "DAUC", "Fille"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "DAUFOST", "Fille placée en famille d'accueil"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "DAUINLAW", "Belle-fille"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "FMRSPS", "Ancien époux ou ancienne épouse"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "FTHFOST", "Assistant familial - Famille d'accueil"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "FTHINLAW", "Beau-père"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GESTM", "Mère porteuse"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GGRPRN", "Arrière-grand-parent"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GRNDCHILD", "Petit-enfant"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "GRPRN", "Grand-parent"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "HSIB", "Demi-frère ou demi-soeur"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "MTHFOST", "Assistante familiale - Famille d'accueil"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "MTHINLAW", "Belle-mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NBRO", "Frère biologique"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NIENEPH", "Neveu ou nièce"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NPRN", "Parent biologique, au sens père ou mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NSIB", "Frère ou soeur biologique"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "NSIS", "Soeur biologique"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "PRN", "Parent, au sens père ou mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "PRNINLAW", "Beau-père ou belle-mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SIB", "Frère ou soeur"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SIBINLAW", "Beau-frère ou belle-soeur"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SIGOTHR", "Conjoint"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SISINLAW", "Belle-soeur"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SONADOPT", "Fils adoptif"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SONC", "Fils"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SONFOST", "Garçon placé en famille d'accueil"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "SONINLAW", "Gendre"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPBRO", "Fils du beau-père ou de la belle-mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPCHLD", "Enfant du conjoint, issu d'un mariage précédent"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPDAU", "Fille du conjoint, issue d'un mariage précédent"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPPRN", "Beau-père ou belle-mère - Époux(se) du père ou de la mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPSIB", "Enfant du beau-père ou de la belle-mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPSIS", "Fille du beau-père ou de la belle-mère"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "STPSON", "Fils du conjoint, issu d'un mariage précédent"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "TWIN", "Frère jumeau ou soeur jumelle"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "TWINBRO", "Frère jumeau"),
            new Coding("https://mos.esante.gouv.fr/NOS/TRE_R216-HL7RoleCode/FHIR/TRE-R216-HL7RoleCode", "TWINSIS", "Soeur jumelle")
    );

    public static Coding getContactRelationship(Person person) {
        return POSSIBLE_RELATIONSHIPS.get(person.randInt(POSSIBLE_RELATIONSHIPS.size()));
    }
}
